### ISSUE TITLE
Proposed feature list

### ISSUE THREAD

**Issue by MrTact** [passwordmaker/chrome-passwordmaker#140]
Hey all. I have been wanting to do some work on this plugin for a while now. Since it's back in active development, I reached out to Eric to find out how to go about this, and he suggested creating a single issue to propose the stuff I'd like to do. And here we are.

I'm mainly interested in two forms of feedback: which features interest you the most, and any concerns you might have (especially from a security standpoint, as, frankly, that's not my area of expertise. I'm more of a usability guy.) Of course, any other input is welcome.

The big list (roughly in the order I would tackle them):
- Auto-remember the last profile used with this host. This would be configurable from the options panel.
- One-click login: If the browser has prepopulated your userid (and we can consistently detect that somehow), your password is stored somewhere, and we have a definitive direction on what profile to use for this host, when you click the button we can just immediately populate the password field and submit the form.
- Store password in memory with expiration: This is a new config option for the General tab, allowing you to store your password in memory, but set a (configurable) window of time after which you will have to type it again. (Because I often just close the lid on my laptop, putting it to sleep, so I have browser sessions that can last for _weeks_.)
- While we're on that subject, is there a reason the password storage option is on the dropdown instead of in the extension settings? Is there anyone who actually changes that regularly, or (as I suspect) does everyone pick one and then forget about it for all time? I can't think of what that use case is. (So I guess the proposed feature is, move it off the dropdown and into settings.)
- Eventually, I would love to make "Keep master password hash" enabled by default, because that feature is awesome and I didn't even know it existed until I started looking at implementing it. This could entail adding a setup experience that would prompt people to enter their master password when they first install the extension.

**Comment by heavensrevenge** [comment]
Hey, I removed the "Save Password" option in the popup.  Any update on your end or if you even use my master branch anymore?

**Comment by heavensrevenge** [comment]
I have removed the "Save Password section from the popup and only have the option in the settings page in my 0.8.8 version.
