### ISSUE TITLE
Problem with option "Hide "Save Password" selection from Popup"

### ISSUE THREAD

**Issue by Auronius** [passwordmaker/chrome-passwordmaker#149]
Good Day!
I am using Opera 30.0.1835.125 on Linux Mint 17.1 x64, and PasswordMaker Pro 0.8.2
I choose the option "Hide "Save Password" selection from Popup". It works normally until I want to disable it again. The problem is, that when I enter at General Options section again, the tick is not near "Hide "Save Password" selection from Popup" options field, so the option is deselected automatically, but the field on the Popup, where I could choose to save password is still hidden. So I cannot bring this field back again! Please fix it.

**Comment by heavensrevenge** [comment]
I'll have a look at it when I'm finished work, thanks for letting me know!

**Comment by heavensrevenge** [comment]
Quick question @Auronius, is the layout somehow messed up? If it looks weird/bad please give me a screenshot of what it looks like.  For now I fixed the little bug you mentioned about the checkbox always being unchecked when going to the options page but if there's a visual problem, mention it now for me. :)

**Comment by Auronius** [comment]
First of all, thank you for continuing support this great application! I wonder why so few people use it...
About your question, seems that the layout is good. http://i.imgur.com/NDs3S8e.jpg

**Comment by heavensrevenge** [comment]
I've got this fixed, I just need to push this to github.
