### ISSUE TITLE
Save password in memory with expiration time is buged.

### ISSUE THREAD

**Issue by Auronius** [passwordmaker/chrome-passwordmaker#150]
Good Day!
I am using Opera 30.0.1835.125 on Linux Mint 17.1 x64, and PasswordMaker Pro 0.8.2
I have choosen option Save password in memory with expiration time 5 minutes:
http://i.imgur.com/Tuqn03o.png
Firstly, when this option is active, PasswordMaker does not generate passwords automatically:
http://i.imgur.com/PHrmewN.png
http://i.imgur.com/Ojg3W9J.png
You need to close the popup window and open it again or type URL address manually, to force it generate the password.
Secondly, I have choosen expiration time 5 minutes, but even after 25 minutes Master Password was still in memory, so this feature is not working at all.
Also, it would be very nice, if the string Manually Verify Password using 3 Letter Code would be in one line, not in separate lines.
http://i.imgur.com/pIsnDPu.png

**Comment by heavensrevenge** [comment]
I've tried this even on a Linux mint vm with opera and haven't been able to reproduce it in the vm.  I did fix an opera bug so when I push an update it might get fixed for you. Otherwise you may need to look into this and tell me where things are going wrong if your able/knowledgeable with debugging JavaScript or send a pr to me if you fix it yourself.  So I won't know until I can see this bug in action since I can't reproduce it or see this behavior.

BTW I fixed that layout bug on your smaller screen resolution.

**Comment by heavensrevenge** [comment]
I pushed 8.3 out so let me know if this fixes the issue whenever it gets approved and reaches you :)

**Comment by Auronius** [comment]
Unfourtunatelly, I am not programmer and can`t debug JavaScripts.
The issue still exists. With option "Save Password: Per Session, expire"  PasswordMaker does not generate passwords automatically.
http://imgur.com/kBmjDRv
And password does not expire even after long time of waiting.
Also cosmetic bug still exists.
http://imgur.com/YT21x2A

**Comment by heavensrevenge** [comment]
Wish i knew what was happening on your end since I can't reproduce this bug on my machine :(  Do you have any friends that know how to debug JavaScript nearby to have a look for me?  That seems like it may be the only way to see whats going on in your computer.

**Comment by Auronius** [comment]
Sorry, but I don't have any friends-programmers. All of them are gone from Latvia, looking for better life in   UK or Netherlands...

**Comment by heavensrevenge** [comment]
@MrTact any way you can have a look at what may be going on here? I can't reproduce this bug so I can't fix what's going on.

**Comment by MrTact** [comment]
I just checked this with Opera 30.0 (albeit on Mac OS X), and I can't repro it either, unfortunately. I'm also not seeing the visual issues that are screenshotted above.

**Comment by Auronius** [comment]
Well, maybe it was a problem with my Linux. Anyway, now i returned to Firefox, and emersion`s Password maker X.
Thank you for your help and fast responses. Good luck in your job and life!
