### ISSUE TITLE
Fill Fields??

### ISSUE THREAD

**Issue by JeremyWW** [passwordmaker/chrome-passwordmaker#152]
Have I been asleep or in a coma or has something changed that I didn't notice? ;-) No 'Fill Fields' button...

**Comment by tasermonkey** [comment]
Though not sure if I am a fan, it appears to only appear when there is a password field to fill.

**Comment by JeremyWW** [comment]
Not appearing for me at all anymore!
____

**Comment by tasermonkey** [comment]
Even on a webpage that has a username/password, after you type in the password?  To me thats when it appears.  Seems to work for me on github and twitter at least.

**Comment by JeremyWW** [comment]
Yep. See attached. I have username and password, both of which work and are filled if you hit enter, but as I'm 'mouse-centric' I'm used to using the 'Fill Fields' button. As you can see it's missing!

![2016-01-25_183019](https://cloud.githubusercontent.com/assets/544340/12560378/456705d4-c392-11e5-9979-703507cd7485.png)

**Comment by tasermonkey** [comment]
I don't know when this changed either.  On chrome's extensions page, it says it hasn't updated since august. https://chrome.google.com/webstore/detail/passwordmaker-pro/lnhofcfhehhcbccpmdmdpjncdoihmkkh?hl=en  But tell you the truth, I didn't noticed it until you pointed it out... and my password maker sync password was cleared, so I assumed something changed.

**Comment by JeremyWW** [comment]
So, is it still being maintained do you know?

**Comment by heavensrevenge** [comment]
I'm looking into this, something messed up with chrome's chrome.tabs.executeScript value being passed into the callback.

**Comment by JeremyWW** [comment]
Great! Cheers.

**Comment by JeremyWW** [comment]
Perfect. Sorted. Thanks.

**Comment by heavensrevenge** [comment]
So you got the update @JeremyWW ? :)

**Comment by JeremyWW** [comment]
Yep :)

**Comment by heavensrevenge** [comment]
Good to hear!
