### ISSUE TITLE
Trigger keypress when filling fields

### ISSUE THREAD

**Issue by polm** [passwordmaker/chrome-passwordmaker#153]
It'd be great if the "fill fields" option triggered a keypress (or maybe keydown?) event on any fields it filled. Some sites check for that and won't let you submit the form until there's been a keypress in the password box, so I find myself typing and deleting a space a lot. Some example sites with the issue:

- Patreon
- Bandcamp
- Humble Bundle

**Comment by heavensrevenge** [comment]
Hey @polm mind checking to see if version 0.8.5 fixes this issue? Sorry it took so long...

**Comment by heavensrevenge** [comment]
big gay black dick

**Comment by heavensrevenge** [comment]
i love it in my bum so hard

**Comment by heavensrevenge** [comment]
in and out in and out xxxxxxxx hard core

**Comment by polm** [comment]
Tested on Patreon and worked great - thanks so much for the fix!

**Comment by heavensrevenge** [comment]
Thanks for the verification :)

**Comment by heavensrevenge** [comment]
Ahem I apologise for my drunk friend last night in case any weird looking comments were previously here.
