### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by Auronius** [passwordmaker/chrome-passwordmaker#154]
Good day!
I have a monitor with resolution 1280x1024. Is it possiple to make, that all lines in Settings menu started after checkbox, not in next line like shown in screenshot.
![passwordmaker](https://cloud.githubusercontent.com/assets/13540006/14314145/53b4c76c-fbfe-11e5-9b94-b24f2880b63c.png)

**Comment by miquelfire** [comment]
It seems the UI has a set length, and it happens to do some wrapping (in strange ways at that)

**Comment by heavensrevenge** [comment]
Yea... I thought I fixed this from setting the label to be nowrap but I'll need to make the row nowrap instead.  It'll get fixed soon :)
Thanks for letting me know @Auronius !

**Comment by heavensrevenge** [comment]
Do you still have this issue @Auronius ?

**Comment by heavensrevenge** [comment]
I may have fixed this issue in the 0.8.5 update with https://github.com/passwordmaker/chrome-passwordmaker/commit/91dd210d9aacc2ef4f82cc1332f1e03b08dd7ac6#diff-02597b8ee65b85b0d098190baa81853aR218 but forgot to mention this in the changelog.
