### ISSUE TITLE
Can't read URL with Vivaldi browser

### ISSUE THREAD

**Issue by rpiotr** [passwordmaker/chrome-passwordmaker#155]
Hi,

I have troubles using passwordmaker with Vivaldi browser (Vivaldi is designed to use Chrome extensions). It looks like passwordmaker can't read current URL from Vivaldi. It results in two things:
- it always use default profile
- "Used text" is always filled with "." (dot) in place of domain name.
  I am not sure if it's a problem of Vivaldi or Passwordmaker.

Regards,

Piotr

**Comment by heavensrevenge** [comment]
Sadly Vivaldi hasn't implemented the "activeTab" permission api and I desire to keep extension permissions to bare minimum for security reasons and not giving the extension "tabs" permissions which would allow reading all tabs and data we will need to wait until Vivaldi gets around to implementing this.

https://developer.chrome.com/extensions/activeTab if you care to have a look why I don't want to go with the "tabs" permission.

If you just want to make it work go into your extension manifest url and change "activeTab" to "tabs" and then it will work for you but I will wait and not fix this yet for the whole ecosystem and prefer Vivaldi to play nice and implement this minimal security permission.

**Comment by rpiotr** [comment]
Hi,

I have changed "activeTab" to "tabs" as you suggested, but it didn't help. But now I understand, that this is the issue of Vivaldi, not PasswordMaker. In the meantime I checked another extension which needs access to URL, and it doesn't work either - even if it has "tabs" permission by default. 
Thanks for explaining !

Regards,

Piotr

**Comment by heavensrevenge** [comment]
Hmm odd, when I change it, it'll work.  After you change it, click the reload link on the extension or just disable then re-enable PasswordMaker Pro after you make the change, it should then work for you in Vivaldi for the time being.

**Comment by rpiotr** [comment]
I did it, and also restarted Vivaldi to be sure. Still the same. Are you using the same version of Vivaldi ? 1.0.435.42 here.

**Comment by heavensrevenge** [comment]
Well I'm not home at the moment to check but I tried it this morning and it worked for me, but I'll check later when I can @rpiotr.

**Comment by rpiotr** [comment]
Hmm... I realized that's it's even more weird...
When I open the page in the new tab manually and click Passwordmaker button it doesn't work. But if I go to the same page by clicking link on another page (but it doesn't work for all pages - I did not find the pattern yet, but it works with links from gmail.com, and facebook.com) then it works correctly. I am confused :(

**Comment by Marenz** [comment]
I tried that change as well and no success for me either.

**Comment by rpiotr** [comment]
I think I found the pattern:
- new tab with new page - does not work
- click on link on page and go to another page - does not work
- right click on a link and open it in new tab - works correctly for all pages
All this regardless what I have in manifest.json.

**Comment by heavensrevenge** [comment]
Funky... Seems they have either changed or only partially allowed how the activeTab permission API functions but thanks for finding this quirk and I hope they fix it's behaviour soon.

And yea I guess they try to prevent changes to an installed extension by hash & keying the ones installed from a store.  I have it working normally by changing the permission in the manifest.json file using my local copy of the extension vs their store version (which you'd need to manually add) and it functions pretty much normally other than auto-focusing the password field.

**Comment by rpiotr** [comment]
Yes, you are right, when Passwordmaker is installed manually it accepts changes in manifest.json. Thanks for help !
