### ISSUE TITLE
doesn't work with angular ng-model=password?

### ISSUE THREAD

**Issue by mmlb** [passwordmaker/chrome-passwordmaker#156]
Ran into an issue using glowing-bear, the dev tried something and it didn't work for me. Is there something else that can be tried?

See https://github.com/glowing-bear/glowing-bear/issues/811

Thanks

**Comment by heavensrevenge** [comment]
OK @mmlb I've updated passwordmaker to hopefully get past angular's view-model state tracking by forcing them to update their state.  I've pushed 0.8.5 and you should be able to try it out soon and see if it works since it worked in my testing.

**Comment by mmlb** [comment]
:woop: it works thanks @heavensrevenge
