### ISSUE TITLE
Make "Use with sites" a multi-line text area

### ISSUE THREAD

**Issue by sunaku** [passwordmaker/chrome-passwordmaker#158]
For usability reasons: It would be easier to maintain a list of domain names in a roomy, multi-line text area than a narrow single-line text field.   Moreover, if newlines were _also_ allowed as delimiters between domain names, then you could list one domain name per line, further improving readability and maintainability.

Thanks for your consideration.

**Comment by heavensrevenge** [comment]
Made this change and I'll upload it soon enough :)
