### ISSUE TITLE
Password is trivially leaked by screen capture

### ISSUE THREAD

**Issue by GlenHertz** [passwordmaker/chrome-passwordmaker#160]
I really like the idea of this password manager but it has a big security hole.  As you are typing in your password the `Verification Code` and `Generated Password` fields are automatically updated.  If you record this information it is trivially easy to find out someone's master password.

For example, if the verification codes for each character typed are:

```
1. CvW
2. GvV
3. frN
4. Tyj
5. bRj
```

Then it will probably take about 2 min to figure out the master password by guessing each character in turn and comparing to the solutions above.  Try it for fun.

The same can be done for recording the `Generated Passwords` but then you also need to know the person's profile information but since that information isn't highly guarded, it should be easy to get.

To fix you should not show the generated information until the person has completed typing in their password (eg after pressing `Enter`)

**Comment by heavensrevenge** [comment]
Hi @GlenHertz , the code used to generate is https://github.com/passwordmaker/chrome-passwordmaker/blob/master/javascript/popup.js#L201 thing is, I've already inserted a forced time delay to try and mitigate this type of reproduction here: https://github.com/passwordmaker/chrome-passwordmaker/blob/master/javascript/popup.js#L72 but maybe the update delay should be longer and/or initiated by pressing Enter.

I added this based on an alternate implementaion of PasswordMaker that used a "verification code" but I can't remember which implemenation initially used it.  But true, if you type slowy and record the generated code it's reversible but if malicious code can watch screen updates it can probably just record key-presses to keylog your master password anyway... local access is a powerful thing.

**Comment by GlenHertz** [comment]
Hi @heavensrevenge, good to see you are trying to mitigate it...I didn't notice it.  I thought the delay was just computation time.  Probably a larger delay would help (like 1.5 seconds) in the short term.  I think updating on pressing `Enter` would be the best for the average user as the person is unlikely to want to verify each key press of their password.  They probably only remember the final verification code to compare against.

With screen sharing and things like that the password could be leaked without local access.  For very sensitive information, plugging one hole is still better (even if there are other holes exist -- like local access).
