### ISSUE TITLE
Feature Request: Support during password change

### ISSUE THREAD

**Issue by manonfgoo** [passwordmaker/chrome-passwordmaker#162]
Hi,

would it be possible to optionally (config flag) have a second password and a second corresponding generated password field? 

Use Case: I do want to update my master password. During transition I need the old and the new generated password.

Thanks,
Manon

**Comment by heavensrevenge** [comment]
Hey @manonfgoo have you ever used the modifier field in the profile configuration?  Just increment it by one or whatever you want when you want to change the password for the site, is that sufficient for you if you've never tried it? That way you don't actually need to change your master password and it'll give a completely different resulting password.

**Comment by b3rnhard** [comment]
That's what I do as well, can recommend as a technique. Also, compromised passwords for a specific site are moved to the next higher number, then I change the password on the site with the new profile.

**Comment by b3rnhard** [comment]
If your master password is compromised you could use a chrome and a firefox both with the extension installed.

**Comment by heavensrevenge** [comment]
Fill passwords one step at a time.  The "Fill Fields" button will fill only one password input element which should be effective enough.  Change profile password generation options in-between filling each input.
