### ISSUE TITLE
Bug: Imported REGEX Fail to Match Profile to Website

### ISSUE THREAD

**Issue by jeremy-harnois** [passwordmaker/chrome-passwordmaker#165]
When importing profiles that use regular expression matching to match a profile to a website, the regular expression match always fails and the profile is never matched.

This appears to be the result of the importer enclosing regex-typed patterns with forward slashes. This makes the pattern a `string` instead of a regular expression `object`, so `RegExp` treats the entire string, including the leading and trailing forward slash, as the pattern, and that pattern doesn't match the URL. It can be replicated by creating a new profile with a pattern similar to `/https:\/\/github\.com\/.*/`, which won't match, and then changing it to `https:\/\/github\.com\/.*`, which will match.

I'm happy to fix, but I wanted to get some input first to make sure I'm not missing anything. I see two possible fixes, either 1) modify the importer to not wrap patterns with slashes, or 2) strip those slashes when trying to match the pattern to the website.

The second approach is a bit less efficient, but it's probably easier, more compatible, and fixes this issue for already imported profiles. The first approach seems more "correct" to me—for whatever that's worth—but it looks like it'll break export compatibility because the slashes are used to determine if the pattern is a regular expression or a wildcard:

    import.js:231] ptype = (pat[0] === "/" && pat[pat.length - 1] === "/") ? "regex" : "wildcard";

I'm leaning towards the second approach. Any objections? Am I missing something that needs to be considered or addressed when fixing this?

**Comment by heavensrevenge** [comment]
I'll look over this, but honestly I would prefer to correct the mistake and fix the importer, if anyone hit the bug like you they should have noticed so I rather have correct behaviour.
Feel free to post a patch.

**Comment by jeremy-harnois** [comment]
Modifying the importer to not wrap the pattern in forward slashes will require adding an additional property to each imported profile to store/track the pattern type so it can be properly set when the profile is exported. Already existing profiles and/or profiles created after importing won't have this property; I'll default to "pattern" since that's what would happen now (I'll test to double check first).

**Comment by heavensrevenge** [comment]
The import & export functionality compensates for the initial oddity as long as the matcher in the popup considers the surrounding slashes right?
If https://github.com/passwordmaker/chrome-passwordmaker/blob/master/javascript/popup.js#L13 is replaced with ` regexString = new RegExp(sites[j].substring(1, sites[j].length - 1));` does everythig work as expected?

**Comment by jeremy-harnois** [comment]
This would also affect regular expressions entered in the extension, which aren't enclosed in forward slashes. Testing first like how it's done when exporting or trimming forward slashes specifically (e.g. `regexString = new RegExp(sites[j].replace(/^\/|\/$/g, ''));`) would probably be better. Although this, too, could adversely affect extension-entered expressions, but I think it'd be a lot less likely and easily worked around by slightly changing the expression.

I suppose the other approach is to turn this bug in to a feature where forward slash–enclosed patterns indicate a regular expression. This would make the importer "correct" while allowing the user to specify that a pattern is a regular expression, and it does so in a way that allows mixing regex and wildcard patterns in the same field. To be honest, that's what I thought was going on when I first saw my imported patterns, but then they didn't match.

**Comment by heavensrevenge** [comment]
I've fixed this but I just need to push the new version up to Google.

**Comment by jeremy-harnois** [comment]
I did, too, but I hadn't had a chance to package it up and create a PR yet, which I've now done. My fix also updates profile matching to use the new `siteListType` profile property I created to fix the issue and exposes that property in profile options.

**Comment by heavensrevenge** [comment]
Have you tried the updated version from the webstore to see it was fixed? Sadly I wasn't able to use your PR :(
