### ISSUE TITLE
Firefox port loses settings and profiles when browser history is cleared

### ISSUE THREAD

**Issue by gwillegers** [passwordmaker/chrome-passwordmaker#171]
When I clear the history of Firefox (ctrl-shift-del), all settings and profiles in Passwordmaker Pro are lost.
The Chrome version does not have this problem.
I am still using this extension side-by-side with the original Passwordmaker. I export settings from there, and import them into Passwordmaker Pro. That saved my @$$. Otherwise losing over 200 profiles would not have been funny.
Things like this are keeping me from upgrading Firefox (still using version 56).

**Comment by heavensrevenge** [comment]
Hey @gwillegers, there is a guy that did his own FF port which I should do... but for now using his version seems to not have that problem with lost state.  The original method of saving data needs to be migrated to the WebExtension way and all be asynchronous vs synchronous.

https://addons.mozilla.org/en-US/firefox/addon/firefox-passwordmaker-pro/ is what he made but I think it'll get you by for now until I make an official FF repo & port.  Hopefully this isn't the only extension holding you back from the FF update from 56.

**Comment by gwillegers** [comment]
No, it is no issue anymore. Sorry, I was unaware that this issue was still open.
I have been using [chrome-passwordmaker](https://github.com/dolohow/chrome-passwordmaker) for several years now.
I just tested it. Clearing browser cache (cookies, history, etc.) does not remove the configuration of passwordmaker.

**Comment by heavensrevenge** [comment]
Good to hear :)
