### ISSUE TITLE
No longer saving password per session

### ISSUE THREAD

**Issue by abudden** [passwordmaker/chrome-passwordmaker#172]
Chrome just updated passwordmaker to a newer version - the icon seems to have changed slightly and the username field has appeared in the window.

I now have to type my master password in every single time, despite having "Save Password" set to "Per Session".

**Comment by heavensrevenge** [comment]
Hmm... this one seems weird.
If you open the extension settings and press F12 to open a console on the setting page, if you enter these 2 things in the console what do they both return?  Shy of reinstalling the extension for a quick fix I'd love to know what these commands return for you.
1 - ` localStorage.getItem("store_location") `
2 - ` Settings.storeLocation `

**Comment by abudden** [comment]
```
1. null
2. "memory"
```

Hope that helps.

**Comment by abudden** [comment]
For what it's worth, my fiancée uses the extension as well and she's having exactly the same problem.

**Comment by heavensrevenge** [comment]
So, if you change the "Save Password" dropdown to something other than Per Session then back again to Per Session what does the command `localStorage.getItem("store_location")` show then? And does the bug still exist if it returns "memory"?

**Comment by abudden** [comment]
Yes, that seems to have fixed it, thank you.

Strange how the option setting got lost though.

**Comment by b3rnhard** [comment]
I am having a similar problem: I have set it to "Per Session" and not "Per Session, Expire", yet it expires after a while. In the past the session lasted as long as my chrome was running.

**Comment by b3rnhard** [comment]
`localStorage.getItem("store_location")` returns `null`

**Comment by b3rnhard** [comment]
@heavensrevenge : Have you been able to reproduce the `memory` option bug or is it working fine with your chrome?

**Comment by halborn** [comment]
This problem exists for me on macos but not on linux.  Not apparent to me how to get the console on Chrome for macos.  F12 isn't it.

**Comment by halborn** [comment]
Found it.
localStorage.getItem("store_location")
"memory"
Settings.storeLocation
"memory"

**Comment by heavensrevenge** [comment]
I pushed out 0.8.9 as an update to hopefully fix this issue.  Can you try making sure your version is at 0.8.9 @halborn and @b3rnhard to see it the bug is fixed?

**Comment by halborn** [comment]
Yes the new update has fixed the problem.  Thanks very much for maintaining this extension.
