### ISSUE TITLE
Import Profiles -> Choose File does not reload the previously already selected file

### ISSUE THREAD

**Issue by b3rnhard** [passwordmaker/chrome-passwordmaker#173]
Version: 0.8.9
When I hit the Choose File button and select a file from my home directory the textbox below won't update its contents if the file was previously already selected. If I switch to another file then back to the first, it will work.

**Comment by b3rnhard** [comment]
I discovered this because I was doing a search'n'replace with a text editor and needed more than one attempt until I was satisfied.

**Comment by heavensrevenge** [comment]
I'm not sure if this is a browser bug or not, Firefox doesn't have the same problem and the content always updates when selecting a file even if it is the same file, but all the Blink-based browsers do have this problem and so does IE... I have tried a few things to try and force the update but there is something fishy in the File API and I haven't been able to fix/force the update of the textarea tag if the same file is re-selected.

**Comment by heavensrevenge** [comment]
Pretty sure this is fixed
