### ISSUE TITLE
Free text field

### ISSUE THREAD

**Issue by ericjacolin** [passwordmaker/chrome-passwordmaker#176]
As a longtime user of PWM of FF I much used the field autopopulate function, mainly for the "user name" fields.
Used to be stored in the legacy RDF fields as:
                   NS1:fieldvalue0="<email address, user name, ...>"
To facilitate the migration to Chrome PWM it would be great to be able to store this information in a free text field. There is no place to store it currently.
The "Username" field is not appropriate for this as it is meant to be used to generate distinct passwords on a same site, and as it takes part in the password calculation.

**Comment by heavensrevenge** [comment]
So kind of like a note stored in a profile without it affecting password generation?

**Comment by ericjacolin** [comment]
Precisely

**Comment by heavensrevenge** [comment]
@ericjacolin I have finally added this as of 0.10.0 the update should be live within a few days.
