### ISSUE TITLE
Get icon back on Menu bar 

### ISSUE THREAD

**Issue by cscj001** [passwordmaker/chrome-passwordmaker#178]
I use PasswordMaker Pro with Chromium under Ubuntu.  The ring that invokes PasswordMaker Pro was on my Menu bar when I installed it.  Somehow it disappeared the other day.  I can get it by clicking the dotted line on the Menu bar.  For some reason, that's where it is.  I would like to get it back on the Menu bar, but all my efforts have been fruitless to date.  Can anyone help with this?

**Comment by shaneonabike** [comment]
This is an option in Chrome where you need to pin specific extensions. You simply need to click the icon (kinda looks like a hammer) to the left of the profile icon. Then pin the ones that you want to display permanently.

**Comment by heavensrevenge** [comment]
Yes this is a browser issue, not an extension issue.
