### ISSUE TITLE
Offered Symbol Only Character Set Is Missing The " \ " Symbol.  Therefore, Passwords Using This CS Will Not Be Backward Compatible With The Original PWM

### ISSUE THREAD

**Issue by GoneToHawaii** [passwordmaker/chrome-passwordmaker#179]
The FULL OFFERED character set in this software version and the original Password Maker is:

ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789`~!@#$%^&*()_-+={}|[]\\\:";'<>?,./

The offered SYMBOL character set in the original Password Maker (1st line example below) is:

`~!@#$%^&*()_-+={}|[]\\\:";'<>?,./

`~!@#$%^&*()_-+={}|[]:";'<>?,./

Note that the offered SYMBOL character set in this (0.8.9) software version (2nd line example above) is different than that of the original Password Maker.

For the offered full character set and the 1st line example of the offered symbol only character set, the " \ " is present but it does NOT appear in the symbol only character set as it does in both character sets of the original Password Maker.

For this current version (0.8.9) to be fully compatible with the original Password Maker, the " \ " symbol must appear in both offered character sets, not just the symbol only offered character set as in this version.

Users will note that when using the offered symbol character set of this version, the generated passwords will be different from that of the original Password Maker when using its offered symbol character set.

Backward compatible passwords using the offered symbol character set of this software version may be created if a correction is made by using the CUSTOM character set option and adding the " \ " symbol in where it is otherwise missing.

A better and more permanent solution would be to edit the this software version to correct and add the symbol " \ " into the offered symbol only character set where it is otherwise missing clearly noting the change such that users are made aware of the correction and of the lack of backwards compatibility with passwords created with software versions that still contained the missing character error at the time said passwords were created.

**Comment by heavensrevenge** [comment]
@GoneToHawaii Good eye, can't believe that missing backslash character in the symbol only character set has been missing for so long and unnoticed...

**Comment by heavensrevenge** [comment]
Fixed with v0.9.2

**Comment by GoneToHawaii** [comment]
Ahh... at last !

Thank you Eric for creating such a simple, useful and long-lasting bit of coding.  I am still enjoying PWM after these many years.

Let's be sure to warn those who need or want backward compatibility of this character set change.

**Comment by heavensrevenge** [comment]
Luckily there's no need, I've tried using the old symbol only character set and after switching to the new extension version, the old buggy one just shows up as a configured custom character set without the backslash. You need to manually change it in the profile options if you want the correct character set to be used.
