### ISSUE TITLE
Export doesn't work with sync data?

### ISSUE THREAD

**Issue by jcam** [passwordmaker/chrome-passwordmaker#184]
I have sync data turned on, which correctly copies the RDF from one instance of chrome to another, but when I attempt to export, the RDF in the export shows what *used to* be on this system, rather than the data from the sync.

**Comment by ericjung** [comment]
This sounds like a sync problem with chrome. What happens if you restart chrome then do the export?

**Comment by heavensrevenge** [comment]
Should be fixed with b6c5402
