### ISSUE TITLE
Site matching fails to use the proper profile

### ISSUE THREAD

**Issue by INeedCaffeine** [passwordmaker/chrome-passwordmaker#185]
I have profiles for both *.aa.com and *.usaa.com.  Whenever I go to usaa.com PWM always selects the profile for aa.com.  

I tried setting the site names to not include wildcards (e.g. aa.com and www.aa.com VS usaa.com or www.usaa.com) but the mismatch still happens.  

I thought it could be an issue with regex's so I tried setting the sites to *(backslash).aa(backslash).com and *(backslash).usaa(backslash).com but the mismatch still happens.  I also tried other expression formats but nothing seems to make PWM properly select the profile for usaa.com when I go to that site; it always selects the aa.com profile.

Is there some secret to making PWM properly match usaa.com with its actual profile or is this a subtle bug in PWM?

Configuration: PasswordMaker (.org) 0.9.1 with Chrome on Windows 10.

Note: The (backslash) above is really the backslash character which GitHub filters out when rendering.

**Comment by ericjung** [comment]
Hi,

this project is not maintained anymore. I recommend you give Noel's passwordmaker ports a try. They are completely compatible with this passwordmaker.

https://github.com/noellh

**Comment by INeedCaffeine** [comment]
FWIW, it looks like Noel's project is dead now.  It has not been updated in ~6 years and the links to the Chrome Store and Google Play both result in 404 responses.

It looks like there is another variant at https://github.com/passwordmaker/chrome-passwordmaker which has picked up the baton for now.  I'll give it a shot.  Thanks!
