### ISSUE TITLE
Extension not working - does not find / offer any profiles to choose from

### ISSUE THREAD

**Issue by datasafeinternationalOfficial** [passwordmaker/chrome-passwordmaker#192]
Title says it all but -- 
when using the chrome extension, it doesn't work (seemingly because it can't find any profiles to choose from).  I've tried exporting, importing profiles, cloning a profile, etc.  Nothing works.

**Comment by heavensrevenge** [comment]
Hmm.. odd, as profile selection works on my end, try reinstalling it or possibly the sync data is messing things up so try resetting sync data if re-adding it doesn't work.

**Comment by heavensrevenge** [comment]
@datasafeinternationalOfficial Come to think of it, it is probably from "fixing" a bug with symbol only character set passwords where it was missing the "\\" (backslash).  Do you remember if you've used symbol only passwords in a profile?

Are you capable of trying some code I give you to run on the extensions options page?

**Comment by datasafeinternationalOfficial** [comment]
Okay you can close this issue.  I removed and re-installed the extension and its working fine now.  I'm not sure why it couldn't see any profiles and [to answer your question], no, I wasn't doing a symbol only profile.  Anyway, thanks for the speedy response.

**Comment by INeedCaffeine** [comment]
I just updated my Chrome to 119 and ran into this same issue.  PWM is not showing any profiles in the pull down list when I go to sites I have accounts for.  However if I open the Options, I see all 300+ sites. 

I tried disabling and re-enabling the extension as well as restarting Chrome but nothing fixed the issue.  I'll try reinstalling the extension and see if that fixes it.

**Comment by heavensrevenge** [comment]
Odd, I'll keep the issue open for others if they run into it over the next few days to know they only need to re-install it.  Hopefully this is a rare bug.

**Comment by heavensrevenge** [comment]
So @INeedCaffeine while on the options page, if you press F12 to open the developer tools, can you see if there is an error mentioned on the "Console" tab?  If there is can you please paste it here to me?  So far I've been unable to reproduce this bug.

**Comment by INeedCaffeine** [comment]
> So @INeedCaffeine while on the options page, if you press F12 to open the developer tools, can you see if there is an error mentioned on the "Console" tab? If there is can you please paste it here to me? So far I've been unable to reproduce this bug.

There is only 1 issue on the Console tab.  A "possible improvement" related to the URL Components not being associated with any form field:

A <label> isn't associated with a form field.
To fix this issue, nest the <input> in the <label> or provide a for attribute on the <label> that matches a form field id.

The Violating node link just highlights the URL Components text.

**Comment by heavensrevenge** [comment]
Darn, the only other thing I can do is request your exported profiles .rdf and import your profiles and hope the bug appears on my end.  Are you willing to share that with me @INeedCaffeine?

**Comment by INeedCaffeine** [comment]
I have been working to reduce the variables as much as I can and still have a reproducible case.  I created a simple 2 entry RDF file for one site and while testing for minimal steps I think I found the key trigger.

The profiles do not show when I use the extension on a site **IF** I simply set the Save Password setting to Never Save.  I found that if I set the Save Password option to **any** other value, the site works just fine.  

I also found that if I simply change the option and then pull up the extension while on the site (no restarting Chrome) the profile will appear and match just fine.  It may take right clicking on the extension a time or two after making the PWM setting change for it to happen but that setting clearly is the trigger.

I'm willing to share my stripped down RDF file and a site URL for you to test with if the new info does not help you reproduce the problem.

**Comment by heavensrevenge** [comment]
HEY that seemed to trigger it for me! Thank you @INeedCaffeine Time to debug :)

**Comment by heavensrevenge** [comment]
Found the bug and fixed https://github.com/passwordmaker/chrome-passwordmaker/commit/3d17fcc0369ea4c62b8daec9acb53f234abc9f39 now @GitTom just has to update the chrome web store version for everyone :slightly_smiling_face:

**Comment by heavensrevenge** [comment]
Had to fix another bug, so it's now 0.9.4 in 85efdb3d @GitTom

**Comment by heavensrevenge** [comment]
Good morning @GitTom will you be able to update your store extension to 0.9.4? If not I had to re-activate my extension https://chrome.google.com/webstore/detail/passwordmaker-pro/lnhofcfhehhcbccpmdmdpjncdoihmkkh to update ~ 400 users... so if @INeedCaffeine wants to verify my fix, by all means.

**Comment by INeedCaffeine** [comment]
I can confirm both 0.9.4 versions fix the issue.  Thanks @heavensrevenge 

Bruce

**Comment by heavensrevenge** [comment]
Right on @INeedCaffeine thank you for verifying! :thumbsup:

**Comment by heavensrevenge** [comment]
The Chrome Web Store just changed to the new url... so I'll have to make another update for https://chromewebstore.google.com/ instead of https://chrome.google.com/ so It'll be 0.9.6

**Comment by heavensrevenge** [comment]
Tagged 0.9.6 d2abff1 for you @GitTom :slightly_smiling_face:
