### ISSUE TITLE
Not copying to clipboard?

### ISSUE THREAD

**Issue by polm** [passwordmaker/chrome-passwordmaker#194]
I recently noticed that the "copy" button doesn't seem to do anything. It's like the extension doesn't have permission to access the clipboard, though I don't get a warning or anything. Is this expected, or is there something I can do to debug it further?

The "fill" button works as usual.

**Comment by heavensrevenge** [comment]
Odd... permissions shouldn't required these days @polm.  I made a few commits to try and fix this.

Could you: 
1. Download https://github.com/passwordmaker/chrome-passwordmaker/archive/refs/heads/master.zip
2. Extract it to your drive
3. Enable the "Developer Mode" in the Extension Manager at chrome://extensions/ 
4. Click "Load Unpacked" 
5. Select the previously extracted folder to install my latest version

Give it a try to see if the bug still persists and report your findings back here?

**Comment by heavensrevenge** [comment]
Any update @polm ?

**Comment by polm** [comment]
Sorry for the delay. I tried the version from master and the copy function works there and it does not work in the version I currently have installed. My current version is 0.9.4 ID  `fckpmekmkjglpmdcbfkchimdelcjiipd`. I am using Linux, Chrome version 119.0.6045.105.

Also, in the currently installed version and the version from master, pushing Enter to fill password fields doesn't work, nothing happens. The fill button itself still works if clicked.

**Comment by polm** [comment]
Anything else I can do to help debug this?

**Comment by heavensrevenge** [comment]
I actually fixed this weeks ago, @GitTom hasn't had the time to update the official version yet.  So @GitTom would you either be able to migrate your (.org) extension to the PasswordMaker group on the Chrome Web Store so I can update it using the 3Dot menu at the top of your extension entry as I have done or update it for your users?  Ideally you migrate it to the publisher group that @miquelfire made so I can handle it atm.

**Comment by GitTom** [comment]
The group invitation has expired - sorry about that.   Can you @miquelfire please invite me again.

**Comment by heavensrevenge** [comment]
Should be updated now @polm.

**Comment by polm** [comment]
Thanks! I confirmed it's working again.
