### ISSUE TITLE
master password confirmation field cursor keeps jumping to first password field

### ISSUE THREAD

**Issue by muecnahc** [passwordmaker/chrome-passwordmaker#197]
master password confirmation field cursor keeps jumping to first password field.  Everytime I stop to shift to CAPS in the confirmation field the cursor jumps to the first field.  Annoying, and just started with latest iteration.

**Comment by heavensrevenge** [comment]
Fixed in e0ef9c7 waiting for it to go live.

**Comment by muecnahc** [comment]
Look forward to the fix.    Much appreciated   
  

  

  

  
  
  
  
  
>

**Comment by heavensrevenge** [comment]
@muecnahc does it appear fixed?

**Comment by muecnahc** [comment]
Yes.    Thx for the quick response.
  

  

  

  
  
  
  
  
>

**Comment by heavensrevenge** [comment]
Glad to help!
